### ISSUE TITLE
vpn over chisel

### ISSUE THREAD

**Issue by shashankmjain** [jpillora/chisel#58] opened 2018-03-26 02:12 UTC
Is there an option to use the tun/tap devices with ssh to have a vpn implemented over chisel instead of doing port forwarding?

**Comment by jpillora** [comment] 2018-03-26 04:33
Possible though outside of the scope of this project, would be a new
project with deeper hooks into the OS with much more OS specific code

**Comment by shashankmjain** [comment] 2018-03-26 04:54
Ok. Thanks. Would be good to have anyways

**Comment by jainsm** [comment] 2018-10-20 05:06
Let us know if you need any contribution?

**Comment by jpillora** [comment] 2018-10-20 14:00
Will close as dupe of #3

**Closed by jpillora** 2018-10-20 14:00 UTC
Labels: enhancement

**Comment by jpillora** [comment] 2018-10-20 14:01
Thanks @jainsm though I think this is out of scope, as it would result in too big of a change. Pulls in requirements around routing and ip address management
