### ISSUE TITLE
Undetected client disconnects

### ISSUE THREAD

**Issue by gvsurenderreddy** [jpillora/chisel#169] opened 2020-07-06 15:53 UTC
Hello sir 
Is there any Default time out from the Client as it stops working from time to time If internet connection reset it doesn't reconnect automatically can you please clarify Please.Thanks for the software is quite faster than FRP.I'm more impressed with its stability from server end.If you can help with UDP and Port Mapping for Port forwarding that would be my ultimate software with good speed more than KCP i guess keep your hard work going thanks again

**Comment by gvsurenderreddy** [comment] 2020-07-12 15:33
Sir chisel stops working from time to to time after few hrs i want to wok always once started is this possible please .Kindly help me.Chisel is great is in many ways its fast than other wstunnel servers

**Comment by jpillora** [comment] 2020-07-12 16:09
What does stop working mean? It fails to reconnect?

**Comment by gvsurenderreddy** [comment] 2020-07-13 06:30
Yes it stop working after a while i need to reboot or restart the Client to make it work

**Comment by asheroto** [comment] 2020-07-14 20:57
I too vote for this.

Basically, if a connection is working but then the client suddenly dies, whether Internet connection or computer issue, then the server keeps "listening" and never times out.  The issue is that when the client comes back up and tries to connect, the server is stuck on "listening" and never re-establishes the connection.  So the only fix right now is to restart the server chisel process.

Tanks!

**Comment by jpillora** [comment] 2020-07-14 20:59
Ah interesting, thanks for info - I think this is indeed a bug

**Comment by gvsurenderreddy** [comment] 2020-07-15 21:04
thanks for accepting Thank you sir much

**Comment by asheroto** [comment] 2020-07-18 22:51
@jpillora did you fix this in the release you just posted?

**Comment by jpillora** [comment] 2020-07-18 23:02
It should be fixed yes, though it’s only a prerelease however the more
testing, the better

**Comment by gvsurenderreddy** [comment] 2020-07-20 01:58
Thank you sir I"ll test and Update you about the same any update for UDP too please

**Comment by jpillora** [comment] 2020-07-22 19:45
Please test `v1.7.0-rc5`, also @gvsurenderreddy, I've added port in use detection

**Comment by asheroto** [comment] 2020-07-22 22:39
Yes, works better, thank you!

**Comment by gvsurenderreddy** [comment] 2020-08-03 07:24
Sir my Question is simple can i have server Port exposed on client.Example I want to connect to ssh on Server port due to firewall I cannot connect to server using ssh So can i use Chisel and connect to server 

Server Side  chisel server --port 33  --reverse 
chisel client 95.217.191.222:33 R:7900:localhost:7900

**Comment by jpillora** [comment] 2020-09-17 12:31
Will close this issue, hopefully its resolved in `v1.7.0`, re-open if not 👍

`R:22:localhost:22` will attempt to listen on 22 on the server, and im guessing it's already running SSH so its in use. I think you want to drop the `R` and connect via the client. Better to open a new issue so this one doesn't get polluted

**Closed by jpillora** 2020-09-17 12:31 UTC
Labels: bug, need-more-info

**Comment by soni-himanshu** [comment] 2024-02-20 09:00
@jpillora is this issue resolved, if Yes in which version and can you share the commit id
